version: 2
jobs:
  test:
    docker:
    - image: cimg/node:latest

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - npm-cache-{{ checksum "package.json" }}

    - run: yarn
    - run: npm install mongoose --no-save
    - run: yarn build && yarn test

    - save_cache:
        paths:
        - node_modules
        key: npm-cache-{{ checksum "package.json" }}

workflows:
  version: 2
  build:
    jobs:
    - test