version: 2
jobs:
  test:
    docker:
    - image: circleci/node:10

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        keys:
        - npm-cache-{{ checksum "package.json" }}

    - run: npm install
    - run: npm install mongoose --no-save
    - run: npm test

    - save_cache:
        paths:
        - node_modules
        key: npm-cache-{{ checksum "package.json" }}

workflows:
  version: 2
  build:
    jobs:
    - lint
    - test